/* Folio UI: selector, draft state, local preview and optional model generation. */
const FORMAT_OPTIONS = [
  { id: 'statistical', icon: '↗', name: 'Datos', note: 'Cifras y hallazgos' },
  { id: 'comparison', icon: '⇄', name: 'Comparar', note: 'A vs. B' },
  { id: 'process', icon: '→', name: 'Proceso', note: 'Paso a paso' },
  { id: 'timeline', icon: '◷', name: 'Cronología', note: 'Antes y después' },
  { id: 'geographic', icon: '⌖', name: 'Mapa', note: 'Lugar y contexto' },
  { id: 'informational', icon: '✦', name: 'Resumen', note: 'Ideas clave' }
];

const FOLDERS = [
  { id: 'calm', name: 'Calmo & claro', note: '3 estilos', caption: 'Una selección serena, modular y fácil de leer.', colors: ['#dcece5','#477c6a','#c8ddd3'], styles: ['senior-clear','boardroom','medico-claro'] },
  { id: 'editorial', name: 'Editorial', note: '3 estilos', caption: 'Texturas, ritmo y un punto más humano.', colors: ['#e9d5bd','#9b5f48','#d6a17c'], styles: ['watercolor-story','handmade-craft','gran-diario'] },
  { id: 'system', name: 'Datos & sistema', note: '4 estilos', caption: 'Precisión visual para explicar lo complejo.', colors: ['#cbdcf0','#32658f','#83a9cf'], styles: ['dashboard-pro','blueprint','timeline-history','heatmap-data'] },
  { id: 'expressive', name: 'Expresivo', note: '4 estilos', caption: 'Más energía, contraste y personalidad.', colors: ['#efd0d0','#d34e55','#f2b955'], styles: ['startup-pitch','cyberpunk-neon','bauhaus-grid','mono-doodle'] }
];

const STYLE_DETAILS = {
  'senior-clear': { folder: 'calm', name: 'Senior Clear', description: 'Accesible y de alto contraste', layout: 'cards' }, 'boardroom': { folder: 'calm', name: 'Boardroom', description: 'Sobrio y corporativo', layout: 'bars' }, 'medico-claro': { folder: 'calm', name: 'Médico claro', description: 'Limpio y tranquilizador', layout: 'cards' },
  'watercolor-story': { folder: 'editorial', name: 'Watercolor Story', description: 'Orgánico y narrativo', layout: 'timeline' }, 'handmade-craft': { folder: 'editorial', name: 'Handmade Craft', description: 'Táctil y artesanal', layout: 'cards' }, 'gran-diario': { folder: 'editorial', name: 'Gran Diario', description: 'Editorial y atemporal', layout: 'bars' },
  'dashboard-pro': { folder: 'system', name: 'Dashboard Pro', description: 'KPIs y módulos de datos', layout: 'bars' }, 'blueprint': { folder: 'system', name: 'Blueprint', description: 'Técnico y estructurado', layout: 'flow' }, 'timeline-history': { folder: 'system', name: 'Timeline History', description: 'Cronológico y didáctico', layout: 'timeline' }, 'heatmap-data': { folder: 'system', name: 'Heatmap Data', description: 'Denso y analítico', layout: 'bars' },
  'startup-pitch': { folder: 'expressive', name: 'Startup Pitch', description: 'Valiente y contemporáneo', layout: 'bars' }, 'cyberpunk-neon': { folder: 'expressive', name: 'Cyberpunk Neon', description: 'Oscuro y futurista', layout: 'flow' }, 'bauhaus-grid': { folder: 'expressive', name: 'Bauhaus Grid', description: 'Geométrico y directo', layout: 'cards' }, 'mono-doodle': { folder: 'expressive', name: 'Mono Doodle', description: 'Cercano y hecho a mano', layout: 'timeline' }
};

const SAMPLES = {
  statistical: { topic: 'Cómo ha cambiado el consumo de agua en España: los hogares gastan más en verano, la ducha representa una parte importante del consumo y pequeños cambios pueden ahorrar litros cada semana.', source: 'Instituto Nacional de Estadística · datos de consumo de los hogares' },
  comparison: { topic: 'Compara trabajar desde casa y desde la oficina según concentración, desplazamientos, colaboración y coste. Resume los beneficios de cada opción y termina con una recomendación según el tipo de equipo.', source: 'Encuesta interna · muestra de 120 personas' },
  process: { topic: 'Explica el proceso en cinco pasos: define una idea central, ordena los datos, elige una metáfora visual, elimina lo que sobra y revisa el resultado con alguien que no conozca el tema.', source: 'Guía interna de comunicación' },
  timeline: { topic: 'Recorre los hitos principales desde los primeros teléfonos móviles hasta los smartphones actuales: tamaño, conectividad, cámara, aplicaciones y el próximo salto hacia la inteligencia artificial.', source: 'Archivo tecnológico · selección de hitos' },
  geographic: { topic: 'Muestra qué regiones producen más energía solar, qué factores lo explican y cómo ha crecido la capacidad instalada. Destaca tres datos y una conclusión útil para quien quiera empezar.', source: 'Informe energético regional · 2025' },
  informational: { topic: 'Resume las cuatro piezas de un hábito sostenible: una señal clara, una acción pequeña, una recompensa cercana y un entorno que facilite repetirlo. Añade un ejemplo práctico para cada idea.', source: 'Resumen de investigación sobre hábitos' }
};

const App = {
  activeFolder: 'system', selectedFormat: 'statistical', selectedStyleId: 'dashboard-pro', lastInfographic: null, toastTimer: null,
  init() {
    this.restoreDraft(); this.renderFormats(); this.renderFolders(); this.renderStyles(); this.bindFields(); this.updateApiStatus(); this.updateTopicCount();
    document.querySelectorAll('input[name="aspect"]').forEach(input => input.addEventListener('change', () => { document.querySelectorAll('.output-option').forEach(option => option.classList.toggle('active', option.querySelector('input').checked)); this.saveDraft(); }));
    document.addEventListener('keydown', e => { if ((e.metaKey || e.ctrlKey) && e.key === 'Enter') this.generate(); if (e.key === 'Escape') { this.closeModelSettings(); this.closeResult(); } });
  },
  getStyle(id = this.selectedStyleId) { return STYLES.find(style => style.id === id) || STYLES[0]; },
  getDetail(id = this.selectedStyleId) { return STYLE_DETAILS[id] || { name: this.getStyle(id).name, description: 'Personalizado', layout: 'cards', folder: this.activeFolder }; },
  renderFormats() { const grid = document.getElementById('format-grid'); grid.innerHTML = FORMAT_OPTIONS.map(option => `<button class="format-option ${option.id === this.selectedFormat ? 'active' : ''}" type="button" data-format="${option.id}" aria-pressed="${option.id === this.selectedFormat}"><span class="format-icon">${option.icon}</span><span class="format-name">${option.name}</span><span class="format-note">${option.note}</span></button>`).join(''); grid.querySelectorAll('.format-option').forEach(button => button.addEventListener('click', () => this.selectFormat(button.dataset.format))); },
  renderFolders() { const tabs = document.getElementById('folder-tabs'); tabs.innerHTML = FOLDERS.map(folder => `<button class="folder-tab ${folder.id === this.activeFolder ? 'active' : ''}" type="button" role="tab" aria-selected="${folder.id === this.activeFolder}" data-folder="${folder.id}"><div class="folder-preview" style="background:${folder.colors[0]};color:${folder.colors[1]}"><span style="height:45%;background:${folder.colors[1]}"></span><span style="height:75%;background:${folder.colors[2]}"></span><span style="height:100%;background:${folder.colors[1]}"></span><span style="height:61%;background:${folder.colors[2]}"></span></div><strong>${folder.name}</strong><small>${folder.note}</small></button>`).join(''); tabs.querySelectorAll('.folder-tab').forEach(button => button.addEventListener('click', () => this.selectFolder(button.dataset.folder))); const folder = FOLDERS.find(item => item.id === this.activeFolder); document.getElementById('folder-caption-text').textContent = folder.caption; },
  renderStyles() { const folder = FOLDERS.find(item => item.id === this.activeFolder); if (!folder) return; if (!folder.styles.includes(this.selectedStyleId)) this.selectedStyleId = folder.styles[0]; const grid = document.getElementById('style-grid'); grid.innerHTML = folder.styles.map(id => this.styleCard(id)).join(''); grid.querySelectorAll('.style-card').forEach(card => card.addEventListener('click', () => this.selectStyle(card.dataset.style))); document.getElementById('visible-style-count').textContent = folder.styles.length; this.renderSelectedStyle(); },
  styleCard(id) { const style = this.getStyle(id); const detail = this.getDetail(id); const colors = [style._c1, style._c2, style._c3, style._c4, style._c5]; let graphic = ''; if (detail.layout === 'bars') graphic = `<div class="preview-bars">${colors.slice(1,5).map(color => `<span style="background:${color}"></span>`).join('')}</div>`; else if (detail.layout === 'timeline') graphic = '<div class="preview-timeline"><i></i><i></i><i></i><i></i></div>'; else if (detail.layout === 'flow') graphic = '<div class="preview-flow"><span></span><b>→</b><span></span><b>→</b><span></span></div>'; else graphic = '<div class="preview-cards"><span></span><span></span><span></span></div>'; const light = this.isLight(colors[0]); const textColor = light ? '#283339' : '#fffefa'; return `<button class="style-card ${id === this.selectedStyleId ? 'active' : ''}" type="button" data-style="${id}" aria-pressed="${id === this.selectedStyleId}"><div class="style-preview" style="background:${colors[0]};color:${textColor}"><div class="preview-kicker" style="color:${colors[2] || textColor}">FOLIO / 01</div><div class="preview-title">Idea<br>en foco</div><div class="preview-line"></div><div class="preview-line short"></div>${graphic}${id === this.selectedStyleId ? '<span class="style-check">✓</span>' : ''}</div><div class="style-info"><strong>${detail.name}</strong><span>${detail.description}</span></div></button>`; },
  renderSelectedStyle() { const style = this.getStyle(); const detail = this.getDetail(); document.getElementById('selected-style').innerHTML = `<span class="selected-swatch" style="background:linear-gradient(135deg,${style._c2},${style._c3})"></span><div><strong>${detail.name}</strong><span>${detail.description}</span></div><span class="selected-tag">seleccionado</span>`; },
  selectFormat(format) { this.selectedFormat = format; this.renderFormats(); this.saveDraft(); }, selectFolder(folder) { this.activeFolder = folder; this.renderFolders(); this.renderStyles(); this.saveDraft(); }, selectStyle(styleId) { this.selectedStyleId = styleId; this.renderStyles(); this.saveDraft(); },
  bindFields() { ['topic','audience','channel','source'].forEach(id => document.getElementById(id).addEventListener('input', () => { this.updateTopicCount(); this.saveDraft(); })); }, updateTopicCount() { const topic = document.getElementById('topic'); document.getElementById('topic-count').textContent = `${topic.value.length} / 900`; },
  loadSample() { const sample = SAMPLES[this.selectedFormat] || SAMPLES.informational; document.getElementById('topic').value = sample.topic; document.getElementById('source').value = sample.source; this.updateTopicCount(); this.saveDraft(); this.showToast('Ejemplo cargado. Puedes editarlo a tu gusto.'); },
  recommend() { const value = document.getElementById('topic').value.toLowerCase(); const format = value.match(/compar|vs\.?|diferenc/) ? 'comparison' : value.match(/paso|proceso|cómo|como|guía/) ? 'process' : value.match(/historia|evoluc|antes|después|cronolog/) ? 'timeline' : value.match(/región|pais|país|ciudad|mapa|lugar/) ? 'geographic' : value.match(/%|porcentaje|datos|aument|disminu|estadíst/) ? 'statistical' : 'informational'; this.selectFormat(format); this.showToast(`Te recomiendo una infografía de ${FORMAT_OPTIONS.find(item => item.id === format).name.toLowerCase()}.`); document.getElementById('format-grid').scrollIntoView({ behavior: 'smooth', block: 'center' }); },
  saveDraft() { const draft = { topic: document.getElementById('topic')?.value || '', audience: document.getElementById('audience')?.value || 'adultos', channel: document.getElementById('channel')?.value || 'social', source: document.getElementById('source')?.value || '', selectedFormat: this.selectedFormat, selectedStyleId: this.selectedStyleId, activeFolder: this.activeFolder, aspect: document.querySelector('input[name="aspect"]:checked')?.value || 'vertical' }; localStorage.setItem('folio-draft', JSON.stringify(draft)); const label = document.getElementById('save-label'); if (label) { label.textContent = 'Guardando…'; clearTimeout(this.saveTimer); this.saveTimer = setTimeout(() => label.textContent = 'Borrador guardado', 420); } },
  restoreDraft() { try { const draft = JSON.parse(localStorage.getItem('folio-draft') || 'null'); if (!draft) return; this.selectedFormat = draft.selectedFormat || this.selectedFormat; this.selectedStyleId = draft.selectedStyleId || this.selectedStyleId; this.activeFolder = draft.activeFolder || this.activeFolder; ['topic','audience','channel','source'].forEach(id => { if (draft[id] !== undefined && document.getElementById(id)) document.getElementById(id).value = draft[id]; }); if (draft.aspect) { const radio = document.querySelector(`input[name="aspect"][value="${draft.aspect}"]`); if (radio) radio.checked = true; } } catch (error) { localStorage.removeItem('folio-draft'); } },
  async generate() { const topic = document.getElementById('topic').value.trim(); if (!topic) { this.showToast('Cuéntame primero qué quieres explicar.'); document.getElementById('topic').focus(); return; } const button = document.getElementById('generate-button'); button.disabled = true; button.innerHTML = '<span class="button-spark">✦</span> Ordenando tu historia…'; const style = this.getStyle(); const apiKey = localStorage.getItem('folio-api-key') || ''; let data; let sourceLabel = 'BOCETO LOCAL'; try { if (apiKey && typeof API !== 'undefined') { const title = topic.split(/[.!?]/)[0].trim().slice(0, 80); data = await API.generate(this.selectedStyleId, document.getElementById('audience').value, title, topic, apiKey); sourceLabel = 'GENERADO CON IA'; } } catch (error) { this.showToast('No se pudo conectar con el modelo; he creado un boceto local para que puedas seguir.'); } if (!data) data = this.makeLocalData(topic); this.lastInfographic = { data, style, sourceLabel, format: this.selectedFormat }; this.renderResult(); button.disabled = false; button.innerHTML = '<span class="button-spark">✦</span> Generar infografía <span class="arrow">→</span>'; },
  makeLocalData(topic) { const title = topic.split(/[.!?]/)[0].trim().slice(0, 72) || 'Una idea en foco'; const sentences = topic.split(/[.!?\n]+/).map(item => item.trim()).filter(Boolean); const base = sentences.length > 1 ? sentences : [topic, 'Ordena la información por capas para facilitar la lectura.', 'Destaca una conclusión que el público pueda recordar.']; const sectionNames = { statistical: ['La señal','Los datos','El contexto','La oportunidad'], comparison: ['Opción A','Opción B','En común','La decisión'], process: ['Empieza','Ordena','Diseña','Revisa'], timeline: ['Origen','Cambio','Salto','Ahora'], geographic: ['Dónde','Qué cambia','Por qué importa','La clave'], informational: ['La idea','Lo esencial','Un ejemplo','La clave'] }[this.selectedFormat] || ['La idea','Lo esencial','La clave']; return { titulo: title, subtitulo: 'Una síntesis visual para entenderlo mejor', fuente: document.getElementById('source').value.trim(), sections: sectionNames.map((name,index) => ({ titulo: name, icono: ['✦','↗','◷','→'][index % 4], dato_destacado: index === 1 ? `${Math.max(24, 68 - index * 9)}%` : '', puntos: [base[index % base.length].slice(0,96), index === 2 ? 'Un detalle que cambia la lectura' : 'Una idea fácil de recordar'] })) }; },
  renderResult() { const result = document.getElementById('result-modal'); const item = this.lastInfographic; const detail = this.getDetail(); document.getElementById('result-style').textContent = detail.name; document.getElementById('result-style-note').textContent = detail.description; document.getElementById('result-format').textContent = (FORMAT_OPTIONS.find(option => option.id === item.format) || FORMAT_OPTIONS[5]).name; document.getElementById('result-format-note').textContent = this.formatNote(item.format); document.getElementById('canvas-badge').textContent = item.sourceLabel; document.getElementById('result-tip').textContent = item.data.fuente ? 'La fuente ya está incorporada. Revisa ahora si los datos necesitan una fecha o enlace.' : 'Añade una fuente para que la pieza pueda circular con más confianza.'; this.drawCanvas(item.data, item.style, item.format); result.hidden = false; document.body.style.overflow = 'hidden'; },
  formatNote(format) { return { statistical:'Cifras y hallazgos', comparison:'Dos opciones, una lectura', process:'Secuencia de acciones', timeline:'Progresión en el tiempo', geographic:'Contexto por lugar', informational:'Jerarquía de ideas' }[format] || 'Lectura rápida'; },
  drawCanvas(data, style, format) { const canvas = document.getElementById('result-canvas'); const aspect = document.querySelector('input[name="aspect"]:checked')?.value || 'vertical'; const width = aspect === 'vertical' ? 720 : 960; const height = aspect === 'vertical' ? 900 : aspect === 'square' ? 760 : 640; canvas.width = width; canvas.height = height; const ctx = canvas.getContext('2d'); const bg = style._c1 || '#1d252b'; const accent = style._c2 || '#f76a4f'; const accent2 = style._c3 || '#f3ca70'; const darkBg = !this.isLight(bg); const text = darkBg ? '#fffefa' : '#1d252b'; const muted = darkBg ? 'rgba(255,254,250,.68)' : 'rgba(29,37,43,.64)'; ctx.fillStyle = bg; ctx.fillRect(0,0,width,height); const gradient = ctx.createLinearGradient(0,0,width,height); gradient.addColorStop(0,this.withAlpha(accent,.18)); gradient.addColorStop(1,this.withAlpha(accent2,.2)); ctx.fillStyle = gradient; ctx.fillRect(0,0,width,height); for (let i=0;i<22;i++) { ctx.fillStyle = this.withAlpha(accent2,.08); ctx.beginPath(); ctx.arc((i*83)%width,(i*137)%height,1.5,0,Math.PI*2); ctx.fill(); } const margin = aspect === 'vertical' ? 48 : 57; ctx.fillStyle = this.withAlpha(accent,.85); ctx.fillRect(margin,46,48,5); ctx.fillStyle = muted; ctx.font = '500 12px DM Mono, monospace'; ctx.fillText('FOLIO / INFOGRAFÍA',margin,77); ctx.fillStyle = text; ctx.font = `700 ${aspect === 'vertical' ? 39 : 42}px Fraunces, Georgia, serif`; this.drawWrapped(ctx,data.titulo || 'Una idea en foco',margin,130,width-margin*2,45,2); ctx.fillStyle = muted; ctx.font = '400 15px DM Sans, Arial, sans-serif'; this.drawWrapped(ctx,data.subtitulo || 'Una síntesis visual para entenderlo mejor',margin,225,width-margin*2,23,2); const top=282; const gap=15; const count=Math.min(data.sections?.length || 4,4); const cardH=aspect === 'vertical' ? 116 : 108; const cardW=aspect === 'vertical' ? width-margin*2 : (width-margin*2-gap)/2; (data.sections || []).slice(0,count).forEach((section,index) => { const x=aspect === 'vertical' ? margin : margin+(index%2)*(cardW+gap); const y=aspect === 'vertical' ? top+index*(cardH+gap) : top+Math.floor(index/2)*(cardH+gap); this.drawSection(ctx,section,x,y,cardW,cardH,index,text,muted,accent,accent2); }); const footerY=height-37; ctx.fillStyle=muted; ctx.font='400 10px DM Mono, monospace'; ctx.fillText(data.fuente ? `FUENTE · ${data.fuente.slice(0,72)}` : 'FOLIO · BOCETO PARA REVISAR',margin,footerY); ctx.fillStyle=accent; ctx.fillRect(width-margin-30,footerY-8,30,2); },
  drawSection(ctx,section,x,y,w,h,index,text,muted,accent,accent2) { ctx.fillStyle=this.withAlpha('#ffffff',.1); ctx.fillRect(x,y,w,h); ctx.fillStyle=[accent,accent2,'#ffffff',accent][index%4]; ctx.fillRect(x,y,5,h); ctx.fillStyle=this.withAlpha(accent2,.88); ctx.beginPath(); ctx.arc(x+27,y+28,14,0,Math.PI*2); ctx.fill(); ctx.fillStyle='#1d252b'; ctx.font='600 13px DM Sans, Arial, sans-serif'; ctx.textAlign='center'; ctx.fillText(section.icono || '✦',x+27,y+33); ctx.textAlign='left'; ctx.fillStyle=text; ctx.font='700 17px Fraunces, Georgia, serif'; ctx.fillText((section.titulo || 'Sección').slice(0,25),x+53,y+29); if (section.dato_destacado) { ctx.fillStyle=accent2; ctx.font='700 23px DM Sans, Arial, sans-serif'; ctx.textAlign='right'; ctx.fillText(section.dato_destacado,x+w-17,y+30); ctx.textAlign='left'; } ctx.fillStyle=muted; ctx.font='400 11px DM Sans, Arial, sans-serif'; this.drawWrapped(ctx,`• ${(section.puntos?.[0] || 'Información relevante para esta sección.').slice(0,120)}`,x+19,y+65,w-38,16,2); },
  drawWrapped(ctx,text,x,y,maxWidth,lineHeight,maxLines) { const words=String(text).split(' '); let line=''; let lines=[]; words.forEach(word => { const test=line ? `${line} ${word}` : word; if (ctx.measureText(test).width > maxWidth && line) { lines.push(line); line=word; } else line=test; }); if (line) lines.push(line); lines=lines.slice(0,maxLines); lines.forEach((item,index) => ctx.fillText(item,x,y+index*lineHeight)); return lines.length; },
  isLight(color) { const hex=(color || '#ffffff').replace('#',''); const r=parseInt(hex.slice(0,2),16) || 255; const g=parseInt(hex.slice(2,4),16) || 255; const b=parseInt(hex.slice(4,6),16) || 255; return (r*299+g*587+b*114)/1000 > 155; }, withAlpha(hex,alpha) { const clean=(hex || '#ffffff').replace('#',''); const r=parseInt(clean.slice(0,2),16) || 255; const g=parseInt(clean.slice(2,4),16) || 255; const b=parseInt(clean.slice(4,6),16) || 255; return `rgba(${r},${g},${b},${alpha})`; },
  openModelSettings() { const modal=document.getElementById('model-modal'); modal.hidden=false; document.getElementById('api-key').value=localStorage.getItem('folio-api-key') || ''; setTimeout(() => document.getElementById('api-key').focus(),30); }, closeModelSettings() { document.getElementById('model-modal').hidden=true; }, saveApiKey() { const key=document.getElementById('api-key').value.trim(); if (key) localStorage.setItem('folio-api-key',key); else localStorage.removeItem('folio-api-key'); this.updateApiStatus(); this.closeModelSettings(); this.showToast(key ? 'Modelo conectado. La próxima pieza se generará con IA.' : 'Modo demo activo.'); }, removeApiKey() { localStorage.removeItem('folio-api-key'); document.getElementById('api-key').value=''; this.updateApiStatus(); this.closeModelSettings(); this.showToast('Modo demo activado.'); }, updateApiStatus() { const connected=Boolean(localStorage.getItem('folio-api-key')); document.getElementById('sidebar-model-status').textContent=connected ? 'Modelo conectado' : 'Modo demo listo'; document.querySelector('.status-dot').style.background=connected ? '#f3ca70' : '#6bc69d'; },
  downloadPNG() { if (!this.lastInfographic) return; const link=document.createElement('a'); link.download=`folio-infografia-${Date.now()}.png`; link.href=document.getElementById('result-canvas').toDataURL('image/png'); link.click(); this.showToast('PNG descargado.'); }, printResult() { window.print(); }, closeResult() { document.getElementById('result-modal').hidden=true; document.body.style.overflow=''; }, regenerate() { this.closeResult(); setTimeout(() => this.generate(),120); }, reset() { localStorage.removeItem('folio-draft'); window.scrollTo({top:0,behavior:'smooth'}); this.showToast('Nuevo borrador listo.'); }, showToast(message) { const toast=document.getElementById('toast'); toast.textContent=message; toast.classList.add('visible'); clearTimeout(this.toastTimer); this.toastTimer=setTimeout(() => toast.classList.remove('visible'),3200); }
};

document.addEventListener('DOMContentLoaded', () => App.init());
