// ============================================================
// INFÓGRAPHIC APP - 50 Estilos con previews visuales
// ============================================================
// Cada estilo genera una preview visual única usando su paleta.
// Las variables _c1.._c5 son los colores para el preview.

const STYLES = [
  // ============ 🧒 INFANTIL ============
  {id:'crayon-kids',name:'Crayon Kids',cat:'infantil',aud:'niños',_c1:'#FF6B35',_c2:'#FFD166',_c3:'#06D6A0',_c4:'#118AB2',_c5:'#EF476F',prompt:'Children crayon drawing style, thick colored strokes, messy playful texture, primary colors, white paper background, child-friendly illustrations, large simple playful text'},
  {id:'cuento-magico',name:'Cuento Mágico',cat:'infantil',aud:'niños',_c1:'#F8EDE3',_c2:'#C9E4DE',_c3:'#C6D8E6',_c4:'#F2C6C6',_c5:'#E8D5C4',prompt:'Storybook illustration style, soft watercolor textures, whimsical animal characters, gentle pastel colors, fairy tale atmosphere, rounded friendly shapes'},
  {id:'lego-brick',name:'Lego Build',cat:'infantil',aud:'niños',_c1:'#E3000F',_c2:'#FFD100',_c3:'#00A3D7',_c4:'#00B159',_c5:'#FF6B00',prompt:'LEGO brick construction style, everything made of colorful interlocking plastic blocks, 3D isometric view, bright toy colors, blocky geometric shapes'},
  {id:'pixel-adventure',name:'Pixel Adventure',cat:'infantil',aud:'niños',_c1:'#2D1B69',_c2:'#FF4365',_c3:'#4BC0C0',_c4:'#FFB347',_c5:'#7B2D8E',prompt:'Retro 8-bit pixel art style, classic video game aesthetic, chunky pixels, limited color palette, game character elements, nostalgic Nintendo-like'},
  {id:'globos-arcoiris',name:'Globos Arcoíris',cat:'infantil',aud:'niños',_c1:'#FF0000',_c2:'#FF7F00',_c3:'#FFFF00',_c4:'#00FF00',_c5:'#0000FF',prompt:'Rainbow themed infographic, hot air balloons, fluffy clouds, colorful gradient sky, joyful whimsical style, bright saturated colors, party atmosphere'},
  {id:'sticker-album',name:'Sticker Album',cat:'infantil',aud:'niños',_c1:'#FF8C94',_c2:'#FAD02C',_c3:'#9DE0AD',_c4:'#45B7D1',_c5:'#FF69B4',prompt:'Sticker album style, cut-out sticker shapes with white borders, glossy shiny effect, collectible card aesthetic, scattered playful layout'},
  {id:'mono-doodle',name:'Mono Doodle',cat:'infantil',aud:'niños',_c1:'#2C2C2C',_c2:'#F5F5F0',_c3:'#8B8B8B',_c4:'#E0E0D8',_c5:'#5C5C5C',prompt:'Monochrome doodle style, black pen on notebook paper, loose sketchy lines, hand-drawn feel, cross-hatching, imperfect organic shapes'},
  {id:'comic-bubble',name:'Comic Bubble',cat:'infantil',aud:'niños',_c1:'#FFD700',_c2:'#FF4500',_c3:'#000000',_c4:'#FFFFFF',_c5:'#00BFFF',prompt:'Comic book style, panel frames with speech bubbles, Ben-Day dots effect, bold black outlines, superhero comic colors, action words with exclamations'},
  {id:'play-doh',name:'Play-Doh',cat:'infantil',aud:'niños',_c1:'#FF1493',_c2:'#FFD700',_c3:'#32CD32',_c4:'#00BFFF',_c5:'#FF6347',prompt:'Play-Doh clay style, squishy puffy 3D shapes, plasticine texture, molded organic forms, bright saturated colors, tactile sculptural appearance'},
  {id:'finger-paint',name:'Finger Paint',cat:'infantil',aud:'niños',_c1:'#E74C3C',_c2:'#F39C12',_c3:'#2ECC71',_c4:'#3498DB',_c5:'#9B59B6',prompt:'Finger painting style, smudged paint textures, handprint marks, messy colorful strokes, thick paint application, tactile child art look'},

  // ============ 👴 SENIOR ============
  {id:'senior-clear',name:'Senior Clear',cat:'senior',aud:'mayores',_c1:'#000000',_c2:'#FFFFFF',_c3:'#FFD700',_c4:'#1A5276',_c5:'#D4E6F1',prompt:'Ultra high contrast infographic for elderly, very large bold font minimum 24pt, black text on white background, simple universal icons, maximum readability, no visual noise, clear sections'},
  {id:'gran-diario',name:'Gran Diario',cat:'senior',aud:'mayores',_c1:'#F5F0E8',_c2:'#2C2C2C',_c3:'#A0522D',_c4:'#8B4513',_c5:'#E8DCC8',prompt:'Large print newspaper style, broadsheet layout, big headlines, serif font, columns of text, classic newsprint beige background, traditional and familiar'},
  {id:'senal-vial',name:'Señal Vial',cat:'senior',aud:'mayores',_c1:'#003399',_c2:'#FFFFFF',_c3:'#FF0000',_c4:'#009900',_c5:'#FFCC00',prompt:'Traffic sign style, universal pictograms, standard signal colors, very simple icons, high contrast, clear bold shapes, instructional clarity like road signs'},
  {id:'medico-claro',name:'Médico Claro',cat:'senior',aud:'mayores',_c1:'#E8F4F8',_c2:'#A8D5E2',_c3:'#1B7A9E',_c4:'#F5F5F5',_c5:'#2C3E50',prompt:'Clean medical clinic style, calming light blue and soft green tones, no distractions, generous white space, large readable type, professional welcoming'},
  {id:'instructivo',name:'Instructivo',cat:'senior',aud:'mayores',_c1:'#FFFFFF',_c2:'#333333',_c3:'#E0E0E0',_c4:'#1565C0',_c5:'#FF6F00',prompt:'IKEA manual style, step-by-step numbered instructions, minimal line drawings, no unnecessary text, clear sequential visual guides, assembly diagram look'},
  {id:'pizarra-blanca',name:'Pizarra Blanca',cat:'senior',aud:'mayores',_c1:'#FFFFFF',_c2:'#000000',_c3:'#E53935',_c4:'#1E88E5',_c5:'#43A047',prompt:'Whiteboard style, black marker on white board, hand-drawn diagrams, simple clear sketches, colored marker accents, easy to follow, classroom clarity'},
  {id:'papel-periodico',name:'Papel Periódico',cat:'senior',aud:'mayores',_c1:'#F4E4C1',_c2:'#8B6914',_c3:'#3E2723',_c4:'#D4A574',_c5:'#6D4C41',prompt:'Vintage newspaper style, sepia tones, aged paper texture, large serif typography, classic print layout, nostalgic historical feel, warm cream colors'},
  {id:'gobierno-claro',name:'Gobierno Claro',cat:'senior',aud:'mayores',_c1:'#0D47A1',_c2:'#FFFFFF',_c3:'#F9A825',_c4:'#1565C0',_c5:'#E3F2FD',prompt:'Official government document style, serious professional layout, flat clean colors, maximum accessibility standards, clear hierarchy, trustworthy institutional'},
  {id:'alta-vista',name:'Alta Vista',cat:'senior',aud:'mayores',_c1:'#000000',_c2:'#FFFF00',_c3:'#FFFFFF',_c4:'#00FF00',_c5:'#00BFFF',prompt:'High visibility dark mode, black background with bright yellow and white text, ultra high contrast for low vision, very large bold fonts, no small details'},
  {id:'calendario',name:'Calendario',cat:'senior',aud:'mayores',_c1:'#F5F0E8',_c2:'#B71C1C',_c3:'#1B5E20',_c4:'#FFFFFF',_c5:'#333333',prompt:'Calendar/almanac style, large date numbers, simple grid layout, familiar monthly calendar format, easy to scan, traditional appointment book feel'},

  // ============ 👔 CORPORATIVO ============
  {id:'boardroom',name:'Boardroom',cat:'corporativo',aud:'adultos',_c1:'#1B2A4A',_c2:'#FFFFFF',_c3:'#C5A55A',_c4:'#2E5C8A',_c5:'#E8ECF1',prompt:'Corporate boardroom style, navy blue and gold, clean elegant lines, professional minimal layout, refined typography, serious business tone'},
  {id:'consulting-dark',name:'Consulting Dark',cat:'corporativo',aud:'adultos',_c1:'#0D1117',_c2:'#FFFFFF',_c3:'#58A6FF',_c4:'#3FB950',_c5:'#D29922',prompt:'Management consulting dark mode, McKinsey-inspired dark background, white charts and graphs, premium data visualization, sophisticated analytical look'},
  {id:'startup-pitch',name:'Startup Pitch',cat:'corporativo',aud:'adultos',_c1:'#6C63FF',_c2:'#FF6584',_c3:'#00C9A7',_c4:'#FFC107',_c5:'#2D3436',prompt:'Startup pitch deck style, modern gradients, bold typography, vibrant accent colors, innovative fresh look, investor-ready presentation aesthetic'},
  {id:'annual-report',name:'Annual Report',cat:'corporativo',aud:'adultos',_c1:'#0A1628',_c2:'#C9A84C',_c3:'#FFFFFF',_c4:'#1B3A5C',_c5:'#D4C8A0',prompt:'Annual report style, navy and gold, premium elegant layout, financial-grade data presentation, sophisticated typography, formal business document'},
  {id:'dashboard-pro',name:'Dashboard Pro',cat:'corporativo',aud:'adultos',_c1:'#1E293B',_c2:'#F8FAFC',_c3:'#3B82F6',_c4:'#10B981',_c5:'#F59E0B',prompt:'Professional dashboard style, KPI widgets and metric cards, data visualization panels, clean modern UI, business intelligence dashboard aesthetic'},
  {id:'legal-blueprint',name:'Legal Blueprint',cat:'corporativo',aud:'adultos',_c1:'#F5F0E8',_c2:'#2C2C2C',_c3:'#8B0000',_c4:'#D4C8A0',_c5:'#4A4A4A',prompt:'Legal document style, formal layout with seals and stamps, parchment-like background, official authoritative tone, serif typeface, legal brief appearance'},
  {id:'newsletter',name:'Newsletter',cat:'corporativo',aud:'adultos',_c1:'#FFFFFF',_c2:'#2D3748',_c3:'#3182CE',_c4:'#ED8936',_c5:'#F7FAFC',prompt:'Email newsletter style, horizontal content bands, clear call-to-action buttons, scannable layout, modern email design, clean dividers between sections'},
  {id:'corporate-memphis',name:'Corporate Memphis',cat:'corporativo',aud:'adultos',_c1:'#FF6B6B',_c2:'#4ECDC4',_c3:'#45B7D1',_c4:'#96CEB4',_c5:'#FFEAA7',prompt:'Corporate Memphis style, flat geometric vector shapes, colorful illustration style, simplified human figures, playful business aesthetic, modern flat design'},
  {id:'slide-deck',name:'Slide Deck',cat:'corporativo',aud:'adultos',_c1:'#FFFFFF',_c2:'#2D3748',_c3:'#4A5568',_c4:'#3182CE',_c5:'#E2E8F0',prompt:'Presentation slide deck style, clean slide layout, subtle dividers, bullet points, professional presentation format, PowerPoint-inspired clean aesthetic'},
  {id:'brand-guide',name:'Brand Guide',cat:'corporativo',aud:'adultos',_c1:'#FFFFFF',_c2:'#1A1A1A',_c3:'#E53935',_c4:'#1E88E5',_c5:'#F5F5F5',prompt:'Brand style guide style, color swatches, typography specimens, clean modular layout, design system documentation, professional brand identity look'},

  // ============ 🎨 ARTÍSTICO ============
  {id:'watercolor-story',name:'Watercolor Story',cat:'artistico',aud:'adultos',_c1:'#D4E6F1',_c2:'#F5CBA7',_c3:'#A9DFBF',_c4:'#F1948A',_c5:'#D2B4DE',prompt:'Watercolor painting style, soft paint bleeds and washes, transparent color layers, organic paint texture, artistic handmade feel, poetic gentle aesthetic'},
  {id:'handmade-craft',name:'Handmade Craft',cat:'artistico',aud:'adultos',_c1:'#F5F0E8',_c2:'#E8D5C4',_c3:'#C9A96E',_c4:'#8B7D6B',_c5:'#D4C8A0',prompt:'Paper cutout craft style, collage aesthetic, torn paper edges, layered paper textures, handmade artisanal feel, physical craft materials look'},
  {id:'cyberpunk-neon',name:'Cyberpunk Neon',cat:'artistico',aud:'adultos',_c1:'#0D0221',_c2:'#FF2D95',_c3:'#00FFF7',_c4:'#7B2D8E',_c5:'#FFD700',prompt:'Cyberpunk neon style, dark futuristic background, glowing neon pink and cyan, holographic effects, grid lines, futuristic dystopian aesthetic, vibrant glow'},
  {id:'origami-fold',name:'Origami Fold',cat:'artistico',aud:'adultos',_c1:'#FFFFFF',_c2:'#E8E0D0',_c3:'#C62828',_c4:'#1565C0',_c5:'#F9A825',prompt:'Origami paper folding style, geometric folded planes, paper texture with fold lines, angular faceted shapes, Japanese paper craft aesthetic, clean folds'},
  {id:'chalkboard',name:'Chalkboard',cat:'artistico',aud:'adultos',_c1:'#2D4A3E',_c2:'#FFFFFF',_c3:'#F5E6CC',_c4:'#E8C37D',_c5:'#A0C4A8',prompt:'Chalkboard style, dark green or blackboard background, white and colored chalk text, chalk dust texture, hand-drawn look, classroom vintage feel'},
  {id:'aged-academia',name:'Aged Academia',cat:'artistico',aud:'adultos',_c1:'#E8D5B7',_c2:'#8B7D6B',_c3:'#3E2723',_c4:'#B71C1C',_c5:'#5D4037',prompt:'Aged academia style, vintage scientific manuscript, sepia toned parchment, hand-drawn scientific diagrams, antique map aesthetic, scholarly historical'},
  {id:'ukiyo-e',name:'Ukiyo-E',cat:'artistico',aud:'adultos',_c1:'#2E4057',_c2:'#D4A574',_c3:'#E8D5B7',_c4:'#4A6FA5',_c5:'#8B4513',prompt:'Japanese Ukiyo-e woodblock print style, Hokusai-inspired, flat natural colors, wave patterns, wood grain texture, traditional Japanese art aesthetic'},
  {id:'bauhaus-grid',name:'Bauhaus Grid',cat:'artistico',aud:'adultos',_c1:'#E53935',_c2:'#1E88E5',_c3:'#FDD835',_c4:'#212121',_c5:'#FFFFFF',prompt:'Bauhaus design style, primary colors red blue yellow, geometric grid layout, constructivist composition, bold blocks of color, German design school aesthetic'},
  {id:'morandi-soft',name:'Morandi Soft',cat:'artistico',aud:'adultos',_c1:'#D4C8B0',_c2:'#B8A99A',_c3:'#C4A882',_c4:'#9E8B72',_c5:'#E8DCC8',prompt:'Morandi color palette style, muted dusty tones, soft greyed colors, Italian painter aesthetic, subtle sophisticated palette, calm gentle visual harmony'},
  {id:'knolling-flat',name:'Knolling Flat',cat:'artistico',aud:'adultos',_c1:'#F5F5F0',_c2:'#2C3E50',_c3:'#E74C3C',_c4:'#3498DB',_c5:'#27AE60',prompt:'Knolling flat lay style, bird\'s eye view, organized objects arranged at right angles, symmetrical layout, neat tidy composition, every item visible clearly'},

  // ============ 📊 TÉCNICO ============
  {id:'lab-report',name:'Lab Report',cat:'tecnico',aud:'adultos',_c1:'#F0F4F8',_c2:'#2D3748',_c3:'#3182CE',_c4:'#38A169',_c5:'#DD6B20',prompt:'Laboratory report style, graph paper grid background, scientific data presentation, precise measurements, clean technical layout, research documentation'},
  {id:'blueprint',name:'Blueprint',cat:'tecnico',aud:'adultos',_c1:'#1A3A5C',_c2:'#FFFFFF',_c3:'#4FC3F7',_c4:'#FFD54F',_c5:'#81C784',prompt:'Engineering blueprint style, deep blue background, white technical lines, measurement callouts, architectural drawing aesthetic, precise drafting look'},
  {id:'subway-map',name:'Subway Map',cat:'tecnico',aud:'adultos',_c1:'#F5F5F0',_c2:'#E53935',_c3:'#1E88E5',_c4:'#43A047',_c5:'#FDD835',prompt:'Subway map diagram style, colored transit lines with stations, route nodes and connections, schematic simplified geography, London tube map inspired'},
  {id:'isometric-tech',name:'Isometric Tech',cat:'tecnico',aud:'adultos',_c1:'#E8ECF1',_c2:'#2C3E50',_c3:'#3498DB',_c4:'#2ECC71',_c5:'#E74C3C',prompt:'Isometric technical style, 30-degree angle 3D perspective, technical diagrams, cube-based layout, exploded view elements, engineering illustration look'},
  {id:'periodic-table',name:'Periodic Table',cat:'tecnico',aud:'adultos',_c1:'#F0F4F8',_c2:'#E74C3C',_c3:'#3498DB',_c4:'#2ECC71',_c5:'#F39C12',prompt:'Periodic table style, grid of categorized cells, color-coded groups, scientific classification layout, chemistry reference aesthetic, element card design'},
  {id:'scientific-paper',name:'Scientific Paper',cat:'tecnico',aud:'adultos',_c1:'#FFFFFF',_c2:'#333333',_c3:'#1565C0',_c4:'#2E7D32',_c5:'#F5F5F5',prompt:'Academic paper style, two-column layout, scientific figures with captions, citation references, scholarly publication format, research journal aesthetic'},
  {id:'flowchart-sys',name:'Flowchart Sys',cat:'tecnico',aud:'adultos',_c1:'#F8FAFC',_c2:'#0F172A',_c3:'#3B82F6',_c4:'#10B981',_c5:'#F59E0B',prompt:'Flowchart diagram style, decision diamonds, process rectangles, arrow connectors, algorithmic logic, system architecture, clear sequential flow'},
  {id:'heatmap-data',name:'Heatmap Data',cat:'tecnico',aud:'adultos',_c1:'#0D1117',_c2:'#440154',_c3:'#3B528B',_c4:'#21918C',_c5:'#5EC962',prompt:'Heatmap data visualization style, color density gradients, data matrix layout, viridis color scale, statistical data representation, analytics dashboard'},
  {id:'timeline-history',name:'Timeline History',cat:'tecnico',aud:'adultos',_c1:'#F5F0E8',_c2:'#8B4513',_c3:'#C9A96E',_c4:'#2C3E50',_c5:'#D4A574',prompt:'Historical timeline style, chronological progression, milestone markers, date annotations, horizontal time axis, historical document aesthetic'},
  {id:'infographic-map',name:'Infographic Map',cat:'tecnico',aud:'adultos',_c1:'#E8F4F8',_c2:'#2E86C1',_c3:'#27AE60',_c4:'#F39C12',_c5:'#E74C3C',prompt:'Geographic infographic map style, colored regions, data overlays on map, location pins, choropleth coloring, cartographic data visualization'}
];
